---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    templateLink: 'https://raw.githubusercontent.com/saumil1991/101-vm-simple-windows-DSC/master/azuredeploy.json'
    paramsLink: 'https://raw.githubusercontent.com/saumil1991/101-vm-simple-windows-DSC/master/azuredeploy.parameters.json'
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: '101-vm-simple-windows-DSC'
        # location seems to be not optional
        location: 'Central India'
        template_link: '{{ templateLink }}'
        parameters_link: '{{ paramsLink }}'